export {PuzzlePage} from './puzzle/puzzle'
export {PavanzadoPage} from './pavanzado/pavanzado';
export {PrincipalPage} from './principal/principal';
export {AbecedarioPage} from './abecedario/abecedario';
export {ColoresPage} from './colores/colores';
export {DiasPage} from './dias/dias';
export {MesesPage} from './meses/meses';
export {NumerosPage} from './numeros/numeros';
export {AnimalesPage} from './animales/animales';
export {MamiferosPage} from './mamiferos/mamiferos';
export {AvesPage} from './aves/aves';
export {PecesPage} from './peces/peces';
export {ReptilesPage} from './reptiles/reptiles';
export {AnfibiosPage} from './anfibios/anfibios';
export {AntropodosPage} from './antropodos/antropodos';
export {IntermedioPage} from './intermedio/intermedio';
export {ProfesionesPage} from './profesiones/profesiones';
export {FrutasPage} from './frutas/frutas';
export {TransportePage} from './transporte/transporte';
export { MaritimoPage} from './maritimo/maritimo';
export {AereoPage} from './aereo/aereo';
export {TerrestrePage} from './terrestre/terrestre';
export {FruhoPage} from './fruho/fruho';
export {HortalizasPage} from './hortalizas/hortalizas';
export {RelojPage} from './reloj/reloj';
export {HoramPage} from './horam/horam';
export {HoratPage} from './horat/horat';
export {AvanzadoPage} from './avanzado/avanzado';
export {CostaPage} from './costa/costa';
export {SierraPage} from './sierra/sierra';
export {OrientePage} from './oriente/oriente';
export {InsularPage} from './insular/insular';
export {ProvinciasPage} from './provincias/provincias';
export {AhorcadoPage} from './ahorcado/ahorcado';
export {TabsPage} from './tabs/tabs';
export {PracticaPage} from './practica/practica';
export {AdivinaPage} from './adivina/adivina';
export {PbasicoPage} from './pbasico/pbasico';
export {JuegocolPage} from './juegocol/juegocol';
export {default as EntradaPage} from './entrada/entrada';
//export {EntradaPage} from './entrada/entrada';
export {FigurasPage} from './figuras/figuras'
export {InformacionPage} from './informacion/informacion'
export {PintermedioPage} from './pintermedio/pintermedio'
export {RegistroPage} from './registro/registro'
export {MoverPage} from './mover/mover'